### PR TITLE
updates bidder module to be 3.0 compliant, and tests

### PR DESCRIPTION
**Pull request by HolzAndrew**
@elberdev @MelodyLi2017 @jasminenoack

### CODE REVIEW

**Comment by MelodyLi2017** [comment]
LGTM

**Comment by jasminenoack** [comment]
Does this go to master or to its own v3 branch? I thought they were separate branches in the project.

**Comment by HolzAndrew** [comment]
> Does this go to master or to its own v3 branch? I thought they were separate branches in the project.

They version control so we don't need to worry about a branch. A publisher would actively have to update to 3.0 in order to get this version of the code.

**Comment by jasminenoack** [comment]
LGTM

**Pull request merged**
