### PR TITLE
add stringified schain

### PR DESCRIPTION
**Pull request by MelodyLi2017**
send stringified json object in GET object + tests

### CODE REVIEW

**Comment by HolzAndrew** [comment]
lgtm. please update when corey confirms and i'll give the 👍

**Comment by MelodyLi2017** [comment]
have been pinging the server with pretty large schains, and it seems to hold up well so feel free to review

**Comment by MelodyLi2017** [comment]
@elberdev @jasminenoack

**Comment by jasminenoack** [comment]
LGTM

**Pull request merged**
